# -*- coding: utf-8 -*-
"""MagneticFieldSim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zWBF2ONIjsxB0_tqNdmRxMwI6CYQPC8
"""

#Magnetic Field and its Gradient Coding
import numpy as np
import numpy.matlib 
# Integration of the Magnetic field and its Gradient
class MagneticFieldSim():

  def __init__(self,P,I):
    self.P=P# microbot posotion
    self.nl=5 #number of coil layers
    self.ntpl=500 #number of turns per layer
    self.Lc=20e-3# length of any coil
    self.p=self.Lc/(2*self.ntpl*np.pi)
    self.nd=1000
    self.Rc=25e-3 #radius of any coil
    self.I=I

    ##Workspace Specifications
    self.Lw=2*self.Rc #length,width and hight of the workspace
    self.CoilPositions=np.array([[self.Lw/2,0,0],[0,self.Lw/2,0],[0,0,self.Lw/2],[-self.Lw/2,0,0],[0,-self.Lw/2,0],[0,0,-self.Lw/2]])#coils positions( x,y,z coordinates for 6x3: 6 coils)
    C=self.CoilPositions
    for j in range(0,6):# the number of coils id wqual to 6
        Cj=C[j,:]
        if   j==0 or j==3 :Cj[0]=C[j,2];Cj[1]=C[j,0];Cj[2]=C[j,1]
        elif j==1 or j==4 :Cj[0]=C[j,0];Cj[1]=C[j,2];Cj[2]=C[j,1]
        elif j==2 or j==5 :Cj[0]=C[j,0];Cj[1]=C[j,1];Cj[2]=C[j,2]

    xc=Cj[0]
    yc=Cj[1]
    zc=Cj[2]
    ntpl=500
    n=1000
    p=self.p
    betah=np.linspace(0,2*ntpl*np.pi,n)
    self.xx=[]
    self.yy=[]
    self.zz=[]
    for j in range(0,6):# the number of coils id wqual to 6
        if   j==0 or j==3 :
            xx=numpy.matlib.repmat(zc,1,n)+self.Rc*np.cos(betah)
            yy=numpy.matlib.repmat(xc,1,n)+self.Rc*np.sin(betah)
            zz=numpy.matlib.repmat(yc,1,n)+np.sign(yc)*2*p*betah 
        elif j==1 or j==4 :
            dbx0=a;dby0=c;dbz0=b;J00[0,:]=d[0,:];J00[1,:]=d[2,:];J00[2,:]=d[1,:]
            xx=numpy.matlib.repmat(xc,1,n)+self.Rc*np.cos(betah)
            yy=numpy.matlib.repmat(zc,1,n)+self.Rc*np.sin(betah)
            zz=numpy.matlib.repmat(yc,1,n)+np.sign(yc)*2*p*betah 
        elif j==2 or j==5 :
            dbx0=a;dby0=b;dbz0=c;J00[0,:]=d[0,:];J00[1,:]=d[1,:];J00[2,:]=d[2,:]
            xx=numpy.matlib.repmat(xc,1,n)+self.Rc*np.cos(betah)
            yy=numpy.matlib.repmat(yc,1,n)+self.Rc*np.sin(betah)
            zz=numpy.matlib.repmat(zc,1,n)+np.sign(zc)*2*p*betah 
        self.xx.append(xx)
        self.yy.append(yy)
        self.yy.append(zz)


     
  def BiotSavar(self):
    beta=self.beta
    dbeta=self.dbeta
    Rc=self.Rc
    p=self.p
    C=self.Cj
    P=self.P
    I=self.Ij
    mu0=4*np.pi*1e-7
    xp=P[0]
    yp=P[1]
    zp=P[2]
    xc=C[0]
    yc=C[1]
    zc=C[2]
    x=xc+Rc*np.cos(beta)
    y=yc+Rc*np.sin(beta)
    z=zc+np.sign(zc)*2*p*beta
    dx=-Rc*np.sin(beta)*dbeta
    dy=Rc*np.cos(beta)*dbeta
    dz=np.sign(zc)*2*p*dbeta
    R=np.sqrt((x-xp)**2+(y-yp)**2+(z-zp)**2)
    if R==0:
        R=0.000000001
    dBx=(mu0*I)/(4*np.pi)*((z-zp)*dy-(y-yp)*dz)/R**3
    dBy=-(mu0*I)/(4*np.pi)*((z-zp)*dx-(x-xp)*dz)/R**3
    dBz=(mu0*I)/(4*np.pi)*((x-xp)*dy-(y-yp)*dx)/R**3
    # if np.isnan(dBx):
    #     dBx=0
    # if np.isnan(dBy):
    #     dBy=0
    # if np.isnan(dBz):
    #     dBz=0
    mu=3*mu0*I/(4*np.pi*R**5)
    dBxdx=mu*((z-zp)*dy-(y-yp)*dz)*(x-xp)
    dBxdy=mu*((z-zp)*(y-yp)*dy+((R**2)/3-(y-yp)**2)*dz)
    dBxdz=-mu*((z-zp)*(y-yp)*dz+((R**2)/3-(z-zp)**2)*dy)
    dBydx=mu*((z-zp)*(x-xp)*dx+((R**2)/3-(x-xp)**2)*dz)
    dBydy=mu*((z-zp)*dx-(x-xp)*dz)*(y-yp)
    dBydz=-mu*((x-xp)*(z-zp)*dz+((R**2)/3-(z-zp)**2)*dx)
    dBzdx=-mu*((x-xp)*(y-yp)*dx+((R**2)/3-(x-xp)**2)*dy)
    dBzdy=mu*((x-xp)*(y-yp)*dy+((R**2)/3-(y-yp)**2)*dx)
    dBzdz=mu*((x-xp)*dy-(y-yp)*dx)*(z-zp)

    J=np.array([[dBxdx,dBxdy,dBxdz],[dBydx,dBydy,dBydz],[dBzdx,dBzdy,dBzdz]])# magnetic field gradient
    return dBx,dBy,dBz,J
  def IntegrationOfBiotSavar(self):
    ntpl=self.ntpl
    nd=self.nd
    C=self.CoilPositions
    Rc=self.Rc
    p=self.p
    I=self.I
    nl=self.nl

    betah=np.linspace(0,2*ntpl*np.pi,nd)
    self.dbeta=2*ntpl*np.pi/nd
    Bx=0
    By=0
    Bz=0
    J=np.array(np.zeros((3,3)))

    for i in range(0,nd):# nd is the size of discretization
      self.beta=betah[i]
      dbx=0
      dby=0
      dbz=0
      J0=np.array(np.zeros((3,3)))
      for j in range(0,6):# the number of coils id wqual to 6
        Cj=C[j,:]
        if   j==0 or j==3 :Cj[0]=C[j,2];Cj[1]=C[j,0];Cj[2]=C[j,1]
        elif j==1 or j==4 :Cj[0]=C[j,0];Cj[1]=C[j,2];Cj[2]=C[j,1]
        elif j==2 or j==5 :Cj[0]=C[j,0];Cj[1]=C[j,1];Cj[2]=C[j,2]

        self.Ij=I[j]
        self.Cj=Cj
        [a,b,c,d]=self.BiotSavar()
        J00=d
        if   j==0 or j==3 :dbx0=c;dby0=a;dbz0=b;J00[0,:]=d[2,:];J00[1,:]=d[0,:];J00[2,:]=d[1,:]
        elif j==1 or j==4 :dbx0=a;dby0=c;dbz0=b;J00[0,:]=d[0,:];J00[1,:]=d[2,:];J00[2,:]=d[1,:]
        elif j==2 or j==5 :dbx0=a;dby0=b;dbz0=c;J00[0,:]=d[0,:];J00[1,:]=d[1,:];J00[2,:]=d[2,:]

        dbx=dbx+dbx0
        dby=dby+dby0
        dbz=dbz+dbz0
        J0=J0+J00
      Bx=Bx+dbx
      By=By+dby
      Bz=Bz+dbz
      J=J+J0
    Bx=nl*Bx  # nl is the number of winding layers
    By=nl*By
    Bz=nl*Bz
    B=np.array([Bx,By,Bz])

    J=nl*J # magnetic field gradient
    return B,J
