# -*- coding: utf-8 -*-
"""MicrobotEnv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpWrnbJTZcmdXI_zBqDwGOGyHUgO8lJE
"""

import numpy as np
import gym
from gym import spaces
from RLMicrobot.microrobotmodel import MicroRobotModel
from RLMicrobot.magneticfieldsim import MagneticFieldSim
from IPython import display
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from IPython.display import clear_output
from RLMicrobot import *
import numpy.matlib

#@title
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

#@title
def rotationmatrix(thx,thy,thz):

  Rotx=np.array([[1, 0, 0,0],[0 ,np.cos(thx), -np.sin(thx),0],[0 ,np.sin(thx), np.cos(thx),0],[0,0,0,1]])
  Roty=np.array([[np.cos(thy) ,0 ,np.sin(thy),0],[0 ,1 ,0,0],[-np.sin(thy), 0, np.cos(thy),0],[0,0,0,1]])
  Rotz=np.array([[np.cos(thz) ,-np.sin(thz), 0,0],[np.sin(thz), np.cos(thz) ,0,0],[0, 0, 1,0],[0,0,0,1]])
  Rot=np.matmul(Rotz,Roty,Rotx)

  return Rot


class Microrobot_Env():


  def __init__(self, state_size, num_actions):

    self.done = 0
    self.reward = 0
    # self.next_state = np.array([0,0,0,0])
    # self.state =np.array([0,0,0,0])
    self.microbot=MicroRobotModel([],[],[])
    self.rm=self.microbot.rm
    self.r1=self.microbot.r1
    self.r2=self.microbot.r2
    self.Rh=self.microbot.Rh
    self.phi=self.microbot.phi

    self.state =[0,0,0,0,0,0]
    self.next_state =[0,0,0,0,0,0]

    self.theta = 0
    self.theta_dot = 0
    self.goal_distance = 3
    self.goal = self.theta + self.goal_distance
    self.target_direction = 1
    self.success_reward = 100
    self.theta_dot = 0
    self.freq_cutoff = 0.8
    self.theta_last = 0
    self.THETA_MARGIN = 3
    self.abort = 0


    self.x=self.rm*np.cos(np.deg2rad(self.theta))
    self.y=self.rm*np.sin(np.deg2rad(self.theta))
    # self.z=0
    self.Ph=0
    self.P=[self.x,self.y,0,1]
    self.microbot.B=[0,0,0]
    self.microbot.J=[[0,0,0],[0,0,0],[0,0,0]]
    self.microbot.P=self.P
    self.microbot.th=np.deg2rad(self.theta)

    self.time=0
    self.phi=0
    # self.target=np.array((self.rm*np.cos(self.goal),self.rm*np.sin(self.goal),0),dtype=np.float32)
    [xt,yt]=pol2cart(self.rm,np.deg2rad(self.goal))
    phit=0
    self.target_cart=[xt,yt,phit]
    self.path=[0,0,0]
    self.step_rate=1
    self.num_actions=num_actions
    self.action_last = np.zeros((num_actions,))

    # self.action_space =np.array([[-1,-1, -1, -1], [1,1, 1, 1]])
    # self.observation_space =np.array([0])
    self.action = np.array(np.random.uniform(-1,1,num_actions))
    self.action_space = spaces.Box(low=-1, high=1, shape=(num_actions,), dtype=np.float32 )
    self.observation_space = spaces.Box(low=0, high=2*np.pi,shape=(1,), dtype=np.float32)
    self.axs=0
    self.testmode=0



  def step(self, action):

    x=self.rm*np.cos(self.state)
    y=self.rm*np.sin(self.state)
    phi=0

    z=0
    rm=self.rm
    Rh=self.Rh
    r1=self.r1
    r2=self.r2
    states = []

    t=self.time

    # M_x = action[0][0]
    # M_y= action[0][1]
    # M_z = max(abs(M_x), abs(M_y))
    # # M_z=action[2]
    # freq = self.freq
    # phi_x = action[0][2]
    # phi_y = action[0][3]

    # thx=freq*t + phi_x*np.pi
    # thy=freq*t + phi_y*np.pi
    # thz=freq*t


    # Ix = M_x*np.sin(thx)#Current in X-axis coil I
    # Iy = M_y*np.sin(thy)#Current in Y-axis coil I
    # Iz = M_z*np.sin(thz)#Current in Z-axis coil I
    Ix=action[0][0]
    Iy=action[0][1]
    Iz=action[0][2]
    # theta_dot = 1.25*freq*M_z*(M_y*sin(phi_y)*sin(th-np.pi/2)+ M_x*sin(phi_x)*sin(th))

    I=[Ix,Iy,Iz,-Ix,-Iy,-Iz]
    self.info=I
    theta=self.state
    P=np.array([rm*np.cos(theta),rm*np.sin(theta),0,1])
    self.P=P
    mag=MagneticFieldSim(P,I)
    [B,J]=mag.IntegrationOfBiotSavar()
    # self.microbot=MicroRobotModel(B,J,theta)
    self.microbot.B=B
    self.microbot.phi=phi
    self.microbot.J=J
    self.microbot.P=P
    self.microbot.th=theta
    [v,w,M]=self.microbot.MicroRobotDyn()

    dt=self.dt
    dx=v[0]*dt
    dy=v[1]*dt
    dphi=0*w[2]*dt

    b=np.sqrt(x**2+y**2)
    x=x+dx
    y=y+dy
    a=np.sqrt(dx**2+dy**2)
    [new_r,new_theta]=cart2pol(x,y)
    c=new_r
    # if theta>=2*np.pi:
    #   new_theta=new_theta-2*np.pi
    # if new_theta<0:
    #   new_theta=new_theta+2*np.pi
    # delth=math.acos((b**2+c**2-a**2)/(2*b*c))

      
    deltheta=np.rad2deg(new_theta-theta)    
    if np.rad2deg(theta)>357 and new_theta<np.rad2deg(3) and new_theta>=0:
        deltheta=abs(deltheta)
    theta=new_theta

    self.microbot.phi=0
    P=np.array([rm*np.cos(theta),rm*np.sin(theta),0,1])
    self.microbot.P=P
    self.microbot.th=theta

    self.theta=np.rad2deg(theta)
    xt=self.target_cart[0]
    yt=self.target_cart[1]
    phit=self.target_cart[2]
    d_target=np.sqrt((xt-x)**2+(yt-y)**2)
    # self.theta = self.correct_for_wrap(self.theta)
    #print(f'theta_dot: {self.theta_dot}')


    # delthg=self.goal-self.theta
    # self.reward = -abs(np.deg2rad(self.goal-self.theta))
    # if abs(self.goal - self.theta) > 300: #assume that theta is 359 and goal is 9, then the difference is 350
    #     self.reward = -abs(np.deg2rad(self.goal+360-self.theta))

    '''if we have reached the goal give success reward and finish the episode'''
    # self.start=self.goal-self.goal_distance
    self.start=self.state
    delths=theta-self.start
    # if self.theta<=self.goal+0.33 and self.theta>=self.start   and deltheta>0   :
    #   if  abs(self.goal-self.theta) <=0.1 :
    #     self.reward+= 10
    #     # self.success = 1
    #     #print('SUCCESS!!!')
    #     self.theta=self.goal
    #     self.done = 1
    #   else:
    #     # self.reward+= -(np.deg2rad(deltheta-5)/(np.pi))**2
    #     self.done = 0

    # elif self.theta<=self.goal and theta>=self.start   and deltheta<=0   :
    #   # self.success = 0
    #   # self.reward+=-2
    #   self.done=3
    # else:
    #   # self.success = 0
    #   # self.reward = -10
    #   self.done=2
    D=(1/100)*(3-deltheta)
    self.reward = -D**2
    if D**2<1e-7 and deltheta>0:
        self.reward =self.reward +10
        self.done=1
    else:
        self.done=0



    self.r1=r1
    self.r2=r2
    self.P=P

    self.next_state =np.deg2rad(self.theta)#,
    self.action_last = action
    return self.next_state, self.reward, self.done ,self.microbot, self.info

  def reset(self):
    self.done = 0
    self.reward = 0
    # th =random.uniform(0, 2*np.pi)
    # r=random.uniform(self.r1, self.r2)
    r=self.rm
    # phi=random.uniform(0, 2*np.pi)
    self.theta = np.random.randint(0,359)

    self.goal = self.theta + self.goal_distance
    # self.goal = self.correct_for_wrap(self.goal)
    # self.state=np.array((r,th,phi),dtype=np.float32)
    # self.state=np.array((r,self.theta),dtype=np.float32)
    # self.state=self.theta
    self.action_last = np.zeros((self.num_actions,))
    [xt,yt]=pol2cart(self.rm,np.deg2rad(self.goal))
    phit=0
    self.target_cart=[xt,yt,phit]

    self.state = np.deg2rad(self.theta )


    return self.state, self.reward, self.done, self.target_cart
  def resetForTest(self):
    self.done = 0
    self.reward = 0
    # th =random.uniform(0, 2*np.pi)
    # r=random.uniform(self.r1, self.r2)
    r=self.rm
    # phi=random.uniform(0, 2*np.pi)
    self.theta = 3

    self.goal = self.theta + self.goal_distance
    # self.goal = self.correct_for_wrap(self.goal)
    # self.state=np.array((r,th,phi),dtype=np.float32)
    # self.state=np.array((r,self.theta),dtype=np.float32)
    # self.state=self.theta
    self.action_last = np.zeros((self.num_actions,))
    [xt,yt]=pol2cart(self.rm,np.deg2rad(self.goal))
    phit=0
    self.target_cart=[xt,yt,phit]

    self.state = np.deg2rad(self.theta )#,

    return self.state, self.reward, self.done, self.target_cart


  def EnvPlot(self):
    fig =plt.figure(figsize=(10,10))
    axs = fig.add_subplot()

    r1=self.r1
    r2=self.r2

    xc1 = 0;yc1 = 0
    angles = np.linspace(0 , 2 * np.pi, 100 )
    xs = np.cos(angles)
    ys = np.sin(angles)
    xc2 = 0
    yc2 = 0;
    fig =plt.figure(figsize=(10,10))
    axs = fig.add_subplot()
    axs.plot(r1*xs, r1*ys, color = 'b')
    axs.plot(r2*xs, r2*ys, color = 'b')
    axs.plot((r1+r2)/2*xs, (r1+r2)/2*ys, color = 'c',linestyle='dashed')
    B=self.microbot.B
    normB= normB=np.sqrt(B[0]**2+B[1]**2+B[2]**2)
    start_cart=self.start_cart
    target_cart=self.target_cart
    P=self.microbot.P
    th=self.microbot.th
    # phi=self.microbot.phi
    Rot=rotationmatrix(0,0,th+np.pi)
    P0=self.microbot.spiralMicroRobot()
    Prot=np.matmul(Rot,P0.T)
    Ph=numpy.matlib.repmat(P,Prot.shape[1],1)+Prot.T # microrbot new position

    plt.plot(Ph[:,0],Ph[:,1],'m')
    # plt.plot( P[0]+Rh*np.cos(np.linspace(0,2*np.pi,20)), P[1]+Rh*np.sin(np.linspace(0,2*np.pi,20)) ,'m' )
    plt.plot( P[0],P[1] ,'ro' )
    # axs.text(path[-1:,0],path[-1,1]+2e-3, 'P', fontsize=12)
    if self.testmode==0:
      plt.plot(start_cart[0],start_cart[1],'bo')
      plt.text(start_cart[0],start_cart[1]-2e-3, 'S', fontsize=12)
      plt.plot(target_cart[0],target_cart[1],'go')
      plt.text(target_cart[0],target_cart[1]+2e-3, 'G', fontsize=12)
      plt.title("S: Start, G: Goal, P:End Position")

    # return fig,axs

  def render(self):

    #display.display(plt.gcf())
    # display.clear_output(wait=0.005)
    # sleep(0.1)
    # plt.close()
    self.EnvPlot()


  def correct_for_wrap(self, angle):
      if angle > 360:
          angle -=360

      if angle < 0:
          angle +=360

      return angle
