# -*- coding: utf-8 -*-
"""MicroRobotModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zWBF2ONIjsxB0_tqNdmRxMwI6CYQPC8
"""

import numpy as np

#@title
class MicroRobotModel():
  def __init__(self,B,J,th):
    self.nh=5 # number of helical circle for microbot
    self.ths=np.array(np.linspace(0,self.nh*2*np.pi,100)) # descritization of angle between 0 and 2*pi
    self.Rh=1*1e-3 #radius of microrbot helical part
    self.b=1.1*self.Rh  # radius of Microrobot head
    self.Lh=4.4e-3  #length of helical part of microrobot
    self.ph=self.Lh/(self.nh*2*np.pi)
    self.etah=2.5*1e-3 # fluid(blood) viscosity
    self.ah=0.05*1e-3  # filament radius
    # self.mh=6e-2 # microrobot moment
    # V=np.pi*self.Rh**2*self.Lhmicrorobot volume V
    X=2e-2# https://journals.sagepub.com/doi/10.5772/58706
    mu0=4*np.pi*1e-7  #denotes the permeability of free space
    self.mh=V*T*(X/(mu0*(1+X)))*B # http://ras.papercept.net/images/temp/IROS/files/3114.pdf
    # where V denotes the volume of the microrobot, X is the susceptibility of the
    # material, T is the ratio of magnetic material volume to the microrobot volume V
    self.B=B
    self.J=J
    self.th=th
    self.r1 = 30*1e-3
    self.r2 = 50*1e-3
    self.rm=(self.r1+self.r2)/2
    self.axs=0
    self.phi=np.pi/4
    self.freq=0.8


  def spiralMicroRobot(self):
    a=self.ph
    r=self.Rh
    ths=self.ths
    shape=np.ndarray((len(ths),4))# shape of microrobot
    for i in range(0,len(ths)):
      if i<2*len(ths)/3:
        r=0.99*r
      else:
        r=0.95*r
      shape[i,:]=np.array([r*np.cos(ths[i]),a*ths[i],r*np.sin(ths[i]),1])# # shape of microrobot

    return shape
#Rotation Matrix


  def helicalMatrix(self):
    n=self.nh
    R=self.Rh
    eta=self.etah
    t=self.ah
    phi=np.pi/4
    b=1.1*R
    Dv=6*np.pi*eta*b
    Dw=8*np.pi*eta*b**3
    em=4*np.pi*eta/(np.log(0.36*np.pi*R/(t*np.sin(phi)))+0.5) #Viscus drag coeficient on normal axis
    en=2*np.pi*eta/np.log(0.36*np.pi*R/(t*np.sin(phi))) #Viscus drag coeficient along cylindrical axis
    A=2*np.pi*n*R*(em*(np.cos(phi))**2+en*(np.sin(phi))**2)/np.sin(phi)-Dv
    B=2*np.pi*n*(R**2)*(em-en)*np.cos(phi)
    D=2*np.pi*n*(R**3)*(en*(np.cos(phi))**2+em*(np.sin(phi)**2))/np.sin(phi)+Dw
    H=np.array([[A,B],[B,D]])
    return H
#  subplot(2,2,1)
  def MicroRobotDyn(self):
    phi=self.phi
    
    X=2e-2# https://journals.sagepub.com/doi/10.5772/58706
    mu0=4*np.pi*1e-7  #denotes the permeability of free space
    self.mh=V*T*(X/(mu0*(1+X)))*self.B # http://ras.papercept.net/images/temp/IROS/files/3114.pdf
    # where V denotes the volume of the microrobot, X is the susceptibility of the
    # material, T is the ratio of magnetic material volume to the microrobot volume V
    mh=self.mh
    ph=self.ph
    rm=self.rm
    B=self.B
    J=self.J

    M=self.mh
    # M=np.array([mh*np.cos(phi) ,mh*np.sin(phi),0] ) #Microrobot magnetization
    tow=np.cross(M,B)# torque implemented on the microrbot by the magnetic filed
    F=np.dot(M,J)# force implemented by magnetic field gradients on the microrobot
    H=self.helicalMatrix()
    T=[F,tow]
    N=np.matmul(np.linalg.inv(H),T)
    v=N[0,:]# micorobot translational velocity after implementing force and torque
    w=N[1,:]# micorobot angular velocity after implementing force and torque
    # phi=np.arctan2(v[1],v[0])
    # L=w[2]*ph
    # dx=L*np.cos(phi)
    # dy=L*np.sin(phi)
    # dvx=v[0]
    # dvy=v[1]
    #delth=np.sign(F[2])*math.atan2(dz,rm) # angle of the movement claculated by "cos law"
    dx=v[0]
    dy=v[1]
    dphi=w[2]
    return v,w,M
