# -*- coding: utf-8 -*-
"""Testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Hag-hRd46zYNvqHbQJ-mzP3nR-r4xGc
"""



"""#Test
When training finished, you can immediately test(only you need to run the related cells fater training sections without need to change(Key='Tset').if you want to test the current Microbot Agent you dont need to use the rar file becuase after running the Microbot agent is updated. in this case you can test without uploading the rar file.
Sometimes you didnt train the code (Key="Test"). in this case, you need to have the updated Microbot agent. if it isnt in colab drive you must upload it if you have previusly created and saved it in your PC drive. in this case,After uploading you can start test section.
"""

# remove the previouse network folder(maybe created by incomplete training)

import shutil
# remove old account directory
if os.path.isdir('/content/Microbot_Agent'):
  shutil.rmtree(r'/content/Microbot_Agent')

# Unrar the network rar file (if the rar file exitis else you mus upload as i said in the previous explanations)

if os.path.isfile('/content/Microbot_Agent.rar'):
  !unrar x "/content/Microbot_Agent.rar" "/content/"
else:
  print('File'+'content/Microbot_Agent.rar'+' doesnt exsit. Please Upload it and after uploading run again this cell to unrrar it')

# if Key=="Test":
max_episod=200
env.dt=0.1
max_step=10
env.max_step=max_step
env.freq=0.8

episode_env_plot=0
step_env_plot=1

rewards, avg_rewards = [], []
best_reward = -np.inf

agent.load_model(gpu_to_cpu=True)

i_episode=-1

env.max_episode=max_episode
state, reward, done,target_cart=env.reset()

k=-1
if os.path.isdir('/content/Images')==1:
  shutil.rmtree(r'/content/Images/')
for episode in range(max_episode):
    env.episode=episode
    i_episode=i_episode+1
    # observation = env.reset()
    done = False
    env.goal = np.rad2deg(state[0]) + env.goal_distance
    [xs,ys]=pol2cart(env.rm, state[0])
    phis=0
    env.start_cart=[xs,ys,phis]
    env.start=state
    i_step=0
    # path[i_step,]=env.start_cart
    #step starting
    env.time=-1
    done=0
    [xt,yt]=pol2cart(env.rm, np.deg2rad(env.goal))
    target_cart=[xt,yt,0,1]
    env.target_cart=target_cart

    while done==0 and i_step<max_step:
        k=k+1
        env.time=env.time+dt
        env.i_step=i_step
        action = agent.choose_action(state, deterministic=True, reparameterize=False)

        next_state, reward, done ,microbot, info= env.step(action)

        env.microbot=microbot
        state = next_state
        env.state = state
        env.action=action
        env.target_cart=target_cart

        [x,y]=pol2cart(env.rm,state[0])
        phi=0
        env.microbot.P=[x,y,0,1]
        env.microbot.th=state[0]

        i_step=i_step+1

        if step_env_plot==1 :
          clear_output(wait=0.005)
          env.render()
          if os.path.isdir('/content/Images')==0:
            os.mkdir('/content/Images')
          plt.savefig("/content/Images/"+str(k)+".png")
          # I=cv2.imread("/content/Images/"+str(k)+".png")
          # cv2.imwrite("/content/images/"+str(k)+".png",I)

"""#Show video"""

img=[]
for i in range(0,500):
      img.append(cv2.imread('/content/Images/'+str(i)+'.png'))

height,width,layers=img[1].shape
frameSize=(height,width)
video = cv2.VideoWriter('output_video.avi',cv2.VideoWriter_fourcc(*'MP4V'), 60, frameSize)

for j in range(0,500):
    video.write(img[j])

cv2.destroyAllWindows()
video.release()